{{- if not .Values.externalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rauthy.fullname" . }}-config
  labels:
    {{- include "rauthy.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |-
    [server]
    scheme = {{ include "rauthy.apiScheme" . | quote }}
    pub_url = {{ include "rauthy.domainName" . | quote }}
    proxy_mode = true
    trusted_proxies = ["10.0.0.0/8"]
    {{- if and .Values.ports.metrics .Values.serviceMonitor.enabled }}
    metrics_enable = true
    metrics_port = {{ int .Values.ports.metrics }}
    {{- end }}

    [cluster]
    node_id_from = "k8s"
    {{- $root := . }}
    {{- $headless := include "rauthy.fullname" . | printf "%s-headless" }}
    {{- if gt (int .Values.replicaCount) 1 }}
    nodes = [
      {{- range $i, $ := until (int $root.Values.replicaCount) }}
        "{{ add $i 1 }} {{ $root.Release.Name }}-{{ $i }}.{{ $headless }}:{{ $root.Values.ports.raft }} {{ $root.Release.Name }}-{{ $i }}.{{ $headless }}:{{ $root.Values.ports.api }}",
      {{- end }}
    ]
    {{- else }}
    nodes = [
        "1 localhost:{{ $root.Values.ports.raft }} localhost:{{ $root.Values.ports.api }}"
    ]
    log_sync = "immediate"
    {{- end }}
    
    secret_raft = "{{ randAlphaNum 48 }}"
    secret_api = "{{ randAlphaNum 48 }}"

    [encryption]
    {{- $randAlphaNum16 := randAlphaNum 16 }}
    keys = [
        "{{ printf "%s/%s" ($randAlphaNum16) (b64enc (randAlphaNum 32)) }}"
    ]
    key_active = "{{ $randAlphaNum16 }}"

    [bootstrap]
    admin_email = "admin@localhost"

    [webauthn]
    rp_id = {{ include "rauthy.domainName" . | quote }}
    rp_origin = {{ include "rauthy.rpOrigin" . | quote }}
    rp_name = "Rauthy"
{{- end }}
