apiVersion: v1
kind: Service
metadata:
  name: {{ include "rauthy.fullname" . }}
  {{ with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rauthy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.scheme }}
      protocol: TCP
      name: {{ .Values.service.scheme }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "rauthy.selectorLabels" . | nindent 4 }}
