[package]
name = "rauthy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
rauthy-common = { path = "../common" }
rauthy-error = { path = "../error" }
rauthy-handlers = { path = "../api" }
rauthy-jwt = { path = "../jwt" }
rauthy-middlewares = { path = "../middlewares" }
rauthy-data = { path = "../data" }
rauthy-schedulers = { path = "../schedulers" }
rauthy-service = { path = "../service" }

actix-web = { workspace = true }
actix-web-prom = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
flume = { workspace = true }
num_cpus = { workspace = true }
openssl = { workspace = true }
openssl-sys = { workspace = true }
prometheus = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }
spow = { workspace = true }
time = { workspace = true }
tls-hot-reload = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }

# jemalloc does not work properly on msvc targets
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, optional = true }

[dev-dependencies]
rauthy-api-types = { path = "../api_types" }

ed25519-compact = { workspace = true }
josekit = "0.8"
pretty_assertions = "1"
reqwest = { workspace = true, features = ["multipart"] }
ring = { workspace = true }
tokio-test = "*"
