name: Code Style

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    if: github.event.pull_request.draft == false
    name: Check Code Style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sebadob/rauthy-builder:20251203
    steps:
      - uses: actions/checkout@v4
      - name: Setup && build UI
        run: |
          just build-wasm
          
          cd frontend
          npm install
          cd ..
          
          just build-ui
      - name: Code Format Backend
        run: cargo fmt --check
      - name: Code Style Backend
        run: cargo clippy -- -D warnings
      - name: Code Format UI
        working-directory: ./frontend
        run: npm run format-check
      - name: Code Style UI
        working-directory: ./frontend
        run: npm run check
